### ISSUE TITLE
Bash entry in README.md

### ISSUE THREAD

**Issue by Chad-Ballay** [adlawson/vagrantfiles#20]
I forgot to add the Bash entry to the README.md.  This is a great beginner issue for making your first Pull Request.
https://hacktoberfest.digitalocean.com/

Here is a good guide on how to make a PR.
https://www.digitalocean.com/community/tutorials/how-to-create-a-pull-request-on-github

I am going to leave this out there until Nov 2nd and then I'll do it myself.

**Comment by prathamsharma92** [comment]
Hello Chad,

What Bash entry need to be added in readme file?

Thanks

**Comment by Chad-Ballay** [comment]
In the README.md file there is a table in the Available Languages section that list the languages with a direct download to the specific vagrantfile.  It also has some additional columns to fill out.  

You should be able to look at how the other entries are formatted and insert the one for the bash.

**Comment by sr6033** [comment]
Can you check #21 and let me know if it is okay?

**Comment by Chad-Ballay** [comment]
Looks like someone got to this first.
